Repository software-architecture-fiap/tech-challenge, pull requests merged in 2024-10, with the labels that each got.

#26 Add infra with Kind and Kustomize
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  Dockerfile
  README.md
  app/model/models.py
  app/model/schemas.py
  app/routers/auth.py
  app/routers/order.py
  app/services/repository.py
  app/services/security.py
  app/tests/test_route_auth.py
  docker-compose.yml
  docs/assets/redoc-init.png
  infra/README.md
  infra/config/kind-config.yaml
  infra/kubernetes/base/deployment-db.yaml
  infra/kubernetes/base/deployment-web.yaml
  infra/kubernetes/base/kustomization.yaml
  infra/kubernetes/base/pvc-db.yaml
  infra/kubernetes/base/pvc-logs.yaml
  infra/kubernetes/base/secrets.yaml
  infra/kubernetes/base/service-db.yaml
  infra/kubernetes/base/service-web.yaml
  infra/kubernetes/development/deployment-patch.yaml
  infra/kubernetes/development/kustomization.yaml
  infra/kubernetes/production/deployment-patch.yaml
  infra/kubernetes/production/kustomization.yaml
  infra/scripts/build-and-publish.sh
  infra/scripts/deploy.sh
  infra/scripts/setup.sh
  poetry.lock
  pyproject.toml
Labels: enhancement

#31 Update kubernetes.md with details about namespaces
  docs/fase_2/kubernetes.md
Labels: documentation

#33 Documentação Final da Fase 2
  .github/CODEOWNERS
  docs/fase_2/kubernetes.md
  docs/fase_2/novas_rotas.md
Labels: documentation

#34 Fix de URL
  docs/fase_2/kubernetes.md
Labels: bug
