Repository software-architecture-fiap/tech-challenge, pull requests merged in 2024-08, with the labels that each got.

#14 Add doc guide: how to test the backend using swagger
  docs/assets/access-token.png
  docs/assets/customer-anon.png
  docs/assets/customer-list.png
  docs/assets/customer-register-result.png
  docs/assets/customer-register.png
  docs/assets/ready_status.png
  docs/assets/response_order.png
  docs/assets/security.png
  docs/assets/token-result.png
  docs/assets/token-token.png
  docs/environment.md
  docs/steps.md
Labels: documentation

#15 Fix Routes Without Hashing
  app/main.py
  app/model/models.py
  app/model/schemas.py
  app/routers/auth.py
  app/routers/category.py
  app/routers/customer.py
  app/routers/order.py
  app/routers/product.py
  app/services/repository.py
  app/services/security.py
  app/tools/initialize_db.py
  app/tools/logging.py
  docs/event-storming.md
  requirements.txt
Labels: bug

#18 Adjusting Read Customer to Not Need Hash
  app/routers/customer.py
Labels: bug

#19 Template de Pull Request
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#22 Create Pep8.yml
  .github/pep8.yml
Labels: enhancement
